name: autogui
description: A cross-platform GUI automation library for Dart. Control mouse and keyboard programmatically on macOS, Windows, and Linux.
version: 1.2.1
repository: https://github.com/0xharkirat/dart_autogui

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.4
  image: ^4.9.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
